import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <ul>
          <li>
            <Link href="/">
              <a data-testid="home">Home</a>
            </Link>
          </li>
          <li>
            <Link href="/about">
              <a data-testid="about">About Us</a>
            </Link>
          </li>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1>Home</h1>
      </main>
    </div>
  );
}
